[package]
name = "aether-bindings"
version = "0.6.0"
authors = ["Aether"]
edition = "2018"
description = "Bindings for CustomMsg and CustomQuery for the Aether blockchain"


[dependencies]
cosmwasm-std = "1.0.0"
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"


[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
